syntax on
"filetype plugin on
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smartindent
set termguicolors
"set cursorline 
set number relativenumber
set incsearch
set hlsearch

colorscheme GruberDarker 


" bindings for moving between widows(:split, :vsplit)  using Ctrl + hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l


" changing size of window with Ctrl + arrow_keys
:nnoremap <C-up> <C-w>+
:nnoremap <C-down> <C-w>-
:nnoremap <C-left> <C-w>>
:nnoremap <C-right> <C-w><

" LSP users are no welcome here ;)
" just use 'tags' utility and grep, for completion, use built in completion
" (Ctrl+N or Ctrl+Space Ctrl + O)
"call plug#begin()
"
"Plug 'prabirshrestha/vim-lsp'
"Plug 'mattn/vim-lsp-settings'
"
"call plug#end()

" copied (almost) directly from the vim-lsp docs:
"function! s:on_lsp_buffer_enabled() abort
"    setlocal omnifunc=lsp#complete
"    setlocal signcolumn=yes
"    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
"
"    let g:lsp_format_sync_timeout = 1000
"    autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')
"endfunction
"
"augroup lsp_install
"    au!
"    " call s:on_lsp_buffer_enabled (set the lsp shortcuts) when an lsp server
"    " is registered for a buffer.
"    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
"augroup END

"inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
"inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
"inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"


" For Vim 8 (<c-@> corresponds to <c-space>):
" imap <c-@> <Plug>(asyncomplete_force_refresh)
